apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: myproject
  labels:
    application: keycloak
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.keycloak: semver:~8.0
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      application: keycloak
  template:
    metadata:
      name: keycloak
      labels:
        application: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:8.0.1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/auth/realms/master"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: "/auth/realms/master"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: DB_VENDOR
              value: "H2"
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: "dns.DNS_PING"
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: "dns_query=keycloak-cluster.myproject.svc.cluster.local"
            - name: CACHE_OWNERS_COUNT
              value: "2"
          securityContext:
            privileged: false
