apiVersion: route.openshift.io/v1
kind: Route
id: keycloak-https
metadata:
  name: keycloak-https
  namespace: myproject
  labels:
    application: keycloak
  annotations:
    description: Route for application's https service.
spec:
  to:
    name: keycloak-https
  tls:
    termination: passthrough